package Server_Java.model.implementations.BoggledApp;


/**
* Client_Java.BoggledApp/AuthenticationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 7:22:27 PM CST
*/


//interface for authentication
public interface AuthenticationOperations 
{
  Player login (String username, String password) throws AccountDoesNotExist, AlreadyLoggedIn;
  void logout (int pid);
} // interface AuthenticationOperations
