package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/Authentication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, May 2, 2024 1:34:29 PM SGT
*/


//interface for authentication
public interface Authentication extends AuthenticationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Authentication
