package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/Authentication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 7:22:27 PM CST
*/


//interface for authentication
public interface Authentication extends AuthenticationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Authentication
