package Server_Java.model.implementations.BoggledApp;

/**
* BoggledApp/GameNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Friday, May 3, 2024 11:23:36 PM SGT
*/

public final class GameNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public GameNotFound value = null;

  public GameNotFoundHolder ()
  {
  }

  public GameNotFoundHolder (GameNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameNotFoundHelper.type ();
  }

}
