package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/GameManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, May 2, 2024 1:34:29 PM SGT
*/


//interface for most of the game methods
public interface GameManager extends GameManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameManager
