package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/GameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Friday, May 10, 2024 3:27:36 PM SGT
*/


//interface for most of the game methods
public interface GameService extends GameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameService
