package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/GameManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 7:22:27 PM CST
*/


//interface for most of the game methods
public abstract class GameManagerPOA extends org.omg.PortableServer.Servant
 implements GameManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("startGame", new java.lang.Integer (0));
    _methods.put ("getWaitingTime", new java.lang.Integer (1));
    _methods.put ("getTotalPlayersJoined", new java.lang.Integer (2));
    _methods.put ("playFirstRound", new java.lang.Integer (3));
    _methods.put ("submitAndLoadNextRound", new java.lang.Integer (4));
    _methods.put ("viewLeaderboards", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BoggledApp/GameManager/startGame
       {
         Player player = PlayerHelper.read (in);
         int $result = (int)0;
         $result = this.startGame (player);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // BoggledApp/GameManager/getWaitingTime
       {
         int gid = in.read_long ();
         int $result = (int)0;
         $result = this.getWaitingTime (gid);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // BoggledApp/GameManager/getTotalPlayersJoined
       {
         int gid = in.read_long ();
         int $result = (int)0;
         $result = this.getTotalPlayersJoined (gid);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // BoggledApp/GameManager/playFirstRound
       {
         int gid = in.read_long ();
         Round $result = null;
         $result = this.playFirstRound (gid);
         out = $rh.createReply();
         RoundHelper.write (out, $result);
         break;
       }


  //returns null if game status is false (no joined players). Otherwise, returns a round (for first round)
       case 4:  // BoggledApp/GameManager/submitAndLoadNextRound
       {
         try {
           String answersArray[] = StringSequenceHelper.read (in);
           int pid = in.read_long ();
           int gid = in.read_long ();
           Round $result = null;
           $result = this.submitAndLoadNextRound (answersArray, pid, gid);
           out = $rh.createReply();
           RoundHelper.write (out, $result);
         } catch (NoPlayersLeft $ex) {
           out = $rh.createExceptionReply ();
           NoPlayersLeftHelper.write (out, $ex);
         }
         break;
       }

       case 5:  // BoggledApp/GameManager/viewLeaderboards
       {
         Player $result[] = null;
         $result = this.viewLeaderboards ();
         out = $rh.createReply();
         PlayerListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoggledApp/GameManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameManager _this() 
  {
    return GameManagerHelper.narrow(
    super._this_object());
  }

  public GameManager _this(org.omg.CORBA.ORB orb) 
  {
    return GameManagerHelper.narrow(
    super._this_object(orb));
  }


} // class GameManagerPOA
