package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/GameManagerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, May 2, 2024 1:34:29 PM SGT
*/


//interface for most of the game methods
public abstract class GameManagerPOA extends org.omg.PortableServer.Servant
 implements GameManagerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("startGame", new java.lang.Integer (0));
    _methods.put ("getRemainingWaitingTime", new java.lang.Integer (1));
    _methods.put ("getNumberOfPlayersJoined", new java.lang.Integer (2));
    _methods.put ("playRound", new java.lang.Integer (3));
    _methods.put ("getRemainingRoundTime", new java.lang.Integer (4));
    _methods.put ("submitWord", new java.lang.Integer (5));
    _methods.put ("getRoundWinner", new java.lang.Integer (6));
    _methods.put ("getGameWinner", new java.lang.Integer (7));
    _methods.put ("leaveGame", new java.lang.Integer (8));
    _methods.put ("getLeaderboards", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // BoggledApp/GameManager/startGame
       {
         int pid = in.read_long ();
         int $result = (int)0;
         $result = this.startGame (pid);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // BoggledApp/GameManager/getRemainingWaitingTime
       {
         int $result = (int)0;
         $result = this.getRemainingWaitingTime ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // BoggledApp/GameManager/getNumberOfPlayersJoined
       {
         int $result = (int)0;
         $result = this.getNumberOfPlayersJoined ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // BoggledApp/GameManager/playRound
       {
         int gid = in.read_long ();
         Round $result = null;
         $result = this.playRound (gid);
         out = $rh.createReply();
         RoundHelper.write (out, $result);
         break;
       }

       case 4:  // BoggledApp/GameManager/getRemainingRoundTime
       {
         int gid = in.read_long ();
         int $result = (int)0;
         $result = this.getRemainingRoundTime (gid);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // BoggledApp/GameManager/submitWord
       {
         String word = in.read_string ();
         int pid = in.read_long ();
         int gid = in.read_long ();
         boolean $result = false;
         $result = this.submitWord (word, pid, gid);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // BoggledApp/GameManager/getRoundWinner
       {
         int gid = in.read_long ();
         String $result = null;
         $result = this.getRoundWinner (gid);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // BoggledApp/GameManager/getGameWinner
       {
         int gid = in.read_long ();
         String $result = null;
         $result = this.getGameWinner (gid);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // BoggledApp/GameManager/leaveGame
       {
         int pid = in.read_long ();
         int gid = in.read_long ();
         this.leaveGame (pid, gid);
         out = $rh.createReply();
         break;
       }

       case 9:  // BoggledApp/GameManager/getLeaderboards
       {
         String $result[] = null;
         $result = this.getLeaderboards ();
         out = $rh.createReply();
         StringSequenceHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:BoggledApp/GameManager:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameManager _this() 
  {
    return GameManagerHelper.narrow(
    super._this_object());
  }

  public GameManager _this(org.omg.CORBA.ORB orb) 
  {
    return GameManagerHelper.narrow(
    super._this_object(orb));
  }


} // class GameManagerPOA
