package Server_Java.model.implementations.BoggledApp;


/**
* Client_Java.BoggledApp/GameManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 7:22:27 PM CST
*/


//interface for most of the game methods
public interface GameManagerOperations 
{
  int startGame (Player player);
  int getWaitingTime (int gid);
  int getTotalPlayersJoined (int gid);
  Round playFirstRound (int gid);

  //returns null if game status is false (no joined players). Otherwise, returns a round (for first round)
  Round submitAndLoadNextRound (String[] answersArray, int pid, int gid) throws NoPlayersLeft;
  Player[] viewLeaderboards ();
} // interface GameManagerOperations
