package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/GameManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Sunday, April 21, 2024 8:36:25 PM CST
*/


//interface for most of the game methods
public interface GameManagerOperations 
{
  int startGame (int pid);
  int getWaitingTime (int gid);
  int getTotalPlayersJoined (int gid);
  Round playFirstRound (int gid);

  //returns null if game status is false (no joined players). Otherwise, returns a round (for first round)
  Round submitAndLoadNextRound (String[] answersArray, int pid, int gid);
  Player[] viewLeaderboards ();
} // interface GameManagerOperations
