package Server_Java.model.implementations.BoggledApp;


/**
* Client_Java.BoggledApp/NoPlayersLeft.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 7:22:27 PM CST
*/

public final class NoPlayersLeft extends org.omg.CORBA.UserException
{
  public String reason = null;

  public NoPlayersLeft ()
  {
    super(NoPlayersLeftHelper.id());
  } // ctor

  public NoPlayersLeft (String _reason)
  {
    super(NoPlayersLeftHelper.id());
    reason = _reason;
  } // ctor


  public NoPlayersLeft (String $reason, String _reason)
  {
    super(NoPlayersLeftHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class NoPlayersLeft
