package Server_Java.model.implementations.BoggledApp;

/**
* BoggledApp/NoPlayersLeftHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 7:22:27 PM CST
*/

public final class NoPlayersLeftHolder implements org.omg.CORBA.portable.Streamable
{
  public NoPlayersLeft value = null;

  public NoPlayersLeftHolder ()
  {
  }

  public NoPlayersLeftHolder (NoPlayersLeft initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = NoPlayersLeftHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    NoPlayersLeftHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return NoPlayersLeftHelper.type ();
  }

}
