package Server_Java.model.implementations.BoggledApp;


/**
* Client_Java.BoggledApp/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 7:22:27 PM CST
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public int pid = (int)0;
  public String fullName = null;
  public String username = null;
  public String password = null;
  public int points = (int)0;
  public int roundsWon = (int)0;

  public Player ()
  {
  } // ctor

  public Player (int _pid, String _fullName, String _username, String _password, int _points, int _roundsWon)
  {
    pid = _pid;
    fullName = _fullName;
    username = _username;
    password = _password;
    points = _points;
    roundsWon = _roundsWon;
  } // ctor

} // class Player
