package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/Round.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Monday, April 22, 2024 6:02:42 PM CST
*/

public final class Round implements org.omg.CORBA.portable.IDLEntity
{
  public int gid = (int)0;
  public Player playersData[] = null;

  //list of players where rounds won and accumulated points can be fetched
  public String characterSet = null;
  public int roundLength = (int)0;
  public int roundNumber = (int)0;
  public Player roundWinner = null;

  //default value = null on first round, only changes after first round when there's a winner
  public Player gameWinner = null;

  public Round ()
  {
  } // ctor

  public Round (int _gid, Player[] _playersData, String _characterSet, int _roundLength, int _roundNumber, Player _roundWinner, Player _gameWinner)
  {
    gid = _gid;
    playersData = _playersData;
    characterSet = _characterSet;
    roundLength = _roundLength;
    roundNumber = _roundNumber;
    roundWinner = _roundWinner;
    gameWinner = _gameWinner;
  } // ctor

} // class Round
