package Server_Java.model.implementations.BoggledApp;


/**
* BoggledApp/Round.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Sunday, April 21, 2024 8:36:25 PM CST
*/

public final class Round implements org.omg.CORBA.portable.IDLEntity
{
  public int gid = (int)0;
  public String players_roundsWon[] = null;

  //a string representation for players' rounds won e.g ["werewolfXD-2", "peterXYZ-1"]
  public int playerAccumulatedPoints = (int)0;
  public String characterSet = null;
  public int roundLength = (int)0;
  public int roundNumber = (int)0;
  public Player roundWinner = null;

  //default value = null on first round, only changes after first round when there's a winner
  public Player gameWinner = null;

  public Round ()
  {
  } // ctor

  public Round (int _gid, String[] _players_roundsWon, int _playerAccumulatedPoints, String _characterSet, int _roundLength, int _roundNumber, Player _roundWinner, Player _gameWinner)
  {
    gid = _gid;
    players_roundsWon = _players_roundsWon;
    playerAccumulatedPoints = _playerAccumulatedPoints;
    characterSet = _characterSet;
    roundLength = _roundLength;
    roundNumber = _roundNumber;
    roundWinner = _roundWinner;
    gameWinner = _gameWinner;
  } // ctor

} // class Round
