package Client_Java.BoggledApp;


/**
* Client_Java.BoggledApp/AuthenticationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Tuesday, April 30, 2024 12:28:41 PM SGT
*/


//interface for authentication
public interface AuthenticationOperations 
{
  Client_Java.BoggledApp.Player login (String username, String password) throws Client_Java.BoggledApp.AccountDoesNotExist, Client_Java.BoggledApp.AlreadyLoggedIn;
  void logout (int pid);
} // interface AuthenticationOperations
