package Client_Java.BoggledApp;


/**
* BoggledApp/Authentication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Friday, May 10, 2024 3:26:55 PM SGT
*/


//interface for authentication
public interface Authentication extends AuthenticationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Authentication
