package Client_Java.BoggledApp;


/**
* Client_Java.BoggledApp/Authentication.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, April 25, 2024 5:31:14 PM CST
*/


//interface for authentication
public interface Authentication extends AuthenticationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Authentication
