package Client_Java.BoggledApp;

/**
* BoggledApp/AuthenticationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, May 2, 2024 1:35:28 PM SGT
*/


//interface for authentication
public final class AuthenticationHolder implements org.omg.CORBA.portable.Streamable
{
  public Authentication value = null;

  public AuthenticationHolder ()
  {
  }

  public AuthenticationHolder (Authentication initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AuthenticationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AuthenticationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AuthenticationHelper.type ();
  }

}
