package Client_Java.BoggledApp;


/**
* Client_Java.BoggledApp/GameManagerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, April 25, 2024 5:31:14 PM CST
*/


//interface for most of the game methods
abstract public class GameManagerHelper
{
  private static String  _id = "IDL:Client_Java.BoggledApp/GameManager:1.0";

  public static void insert (org.omg.CORBA.Any a, Client_Java.BoggledApp.GameManager that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Client_Java.BoggledApp.GameManager extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Client_Java.BoggledApp.GameManagerHelper.id (), "GameManager");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Client_Java.BoggledApp.GameManager read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameManagerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Client_Java.BoggledApp.GameManager value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Client_Java.BoggledApp.GameManager narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Client_Java.BoggledApp.GameManager)
      return (Client_Java.BoggledApp.GameManager)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Client_Java.BoggledApp._GameManagerStub stub = new Client_Java.BoggledApp._GameManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Client_Java.BoggledApp.GameManager unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Client_Java.BoggledApp.GameManager)
      return (Client_Java.BoggledApp.GameManager)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Client_Java.BoggledApp._GameManagerStub stub = new Client_Java.BoggledApp._GameManagerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
