package Client_Java.BoggledApp;


/**
* BoggledApp/GameManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Friday, May 3, 2024 11:23:17 PM SGT
*/


//interface for most of the game methods
public interface GameManagerOperations 
{
  int startGame (int pid);
  int getRemainingWaitingTime () throws GameTimeOut;
  int getNumberOfPlayersJoined ();
  Round playRound (int gid) throws GameNotFound;
  int getRemainingRoundTime (int gid) throws GameTimeOut;
  boolean submitWord (String word, int pid, int gid);
  String getRoundWinner (int gid);
  String getGameWinner (int gid);
  void leaveGame (int pid, int gid);
  String[] getLeaderboards ();
} // interface GameManagerOperations
