package Client_Java.BoggledApp;


/**
* BoggledApp/GameManagerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, May 2, 2024 1:35:28 PM SGT
*/


//interface for most of the game methods
public interface GameManagerOperations 
{
  int startGame (int pid);
  int getRemainingWaitingTime ();
  int getNumberOfPlayersJoined ();
  Round playRound (int gid);
  int getRemainingRoundTime (int gid);
  boolean submitWord (String word, int pid, int gid);
  String getRoundWinner (int gid);
  String getGameWinner (int gid);
  void leaveGame (int pid, int gid);
  String[] getLeaderboards ();
} // interface GameManagerOperations
