package Client_Java.BoggledApp;


/**
* Client_Java.BoggledApp/GameManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Tuesday, April 30, 2024 12:28:41 PM SGT
*/


//interface for most of the game methods
public interface GameManager extends GameManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameManager
