package Client_Java.BoggledApp;


/**
* BoggledApp/GameManager.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Friday, May 3, 2024 4:33:21 PM SGT
*/


//interface for most of the game methods
public interface GameManager extends GameManagerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameManager
