package Client_Java.BoggledApp;


/**
* BoggledApp/InvalidWord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Friday, May 10, 2024 6:34:33 AM SGT
*/

public final class InvalidWord extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidWord ()
  {
    super(InvalidWordHelper.id());
  } // ctor

  public InvalidWord (String _reason)
  {
    super(InvalidWordHelper.id());
    reason = _reason;
  } // ctor


  public InvalidWord (String $reason, String _reason)
  {
    super(InvalidWordHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidWord
