package Client_Java.BoggledApp;


/**
* Client_Java.BoggledApp/PlayerListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, April 25, 2024 5:31:14 PM CST
*/


// sequence of players
abstract public class PlayerListHelper
{
  private static String  _id = "IDL:Client_Java.BoggledApp/PlayerList:1.0";

  public static void insert (org.omg.CORBA.Any a, Client_Java.BoggledApp.Player[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Client_Java.BoggledApp.Player[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = Client_Java.BoggledApp.PlayerHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (Client_Java.BoggledApp.PlayerListHelper.id (), "PlayerList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Client_Java.BoggledApp.Player[] read (org.omg.CORBA.portable.InputStream istream)
  {
    Client_Java.BoggledApp.Player value[] = null;
    int _len0 = istream.read_long ();
    value = new Client_Java.BoggledApp.Player[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = Client_Java.BoggledApp.PlayerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Client_Java.BoggledApp.Player[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      Client_Java.BoggledApp.PlayerHelper.write (ostream, value[_i0]);
  }

}
