package Client_Java.BoggledApp;

/**
* Client_Java.BoggledApp/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, April 25, 2024 5:31:14 PM CST
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public Client_Java.BoggledApp.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (Client_Java.BoggledApp.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Client_Java.BoggledApp.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Client_Java.BoggledApp.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Client_Java.BoggledApp.PlayerHelper.type ();
  }

}
