package Client_Java.BoggledApp;


/**
* Client_Java.BoggledApp/Round.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA IDL.idl
* Thursday, April 25, 2024 5:31:14 PM CST
*/

public final class Round implements org.omg.CORBA.portable.IDLEntity
{
  public int gid = (int)0;
  public Client_Java.BoggledApp.Player playersData[] = null;

  //list of players where rounds won and accumulated points can be fetched
  public String characterSet = null;
  public int roundLength = (int)0;
  public int roundNumber = (int)0;
  public Client_Java.BoggledApp.Player roundWinner = null;

  //default value = null on first round, only changes after first round when there's a winner
  public Client_Java.BoggledApp.Player gameWinner = null;

  public Round ()
  {
  } // ctor

  public Round (int _gid, Client_Java.BoggledApp.Player[] _playersData, String _characterSet, int _roundLength, int _roundNumber, Client_Java.BoggledApp.Player _roundWinner, Client_Java.BoggledApp.Player _gameWinner)
  {
    gid = _gid;
    playersData = _playersData;
    characterSet = _characterSet;
    roundLength = _roundLength;
    roundNumber = _roundNumber;
    roundWinner = _roundWinner;
    gameWinner = _gameWinner;
  } // ctor

} // class Round
